application: knurekapi
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/friends/
  script: src.friends.app

- url: /api/auth/
  script: src.auth.app

builtins:
- deferred: on

