application: knurekapi
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /api/friends/sync/.*
  script: src.friends.app

- url: /api/friends/.*/avatar
  script: src.avatar.app

- url: /api/auth/
  script: src.auth.app

- url: /.*
  static_files: static/html/404.html
  upload: static/html/404.html

builtins:
- deferred: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
